version: '3.8'

services:
  auth_db:
    image: postgres:15
    container_name: auth_db
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: ${AUTH_DB_USER}
      POSTGRES_PASSWORD: ${AUTH_DB_PASS}
    ports:
      - "5432:5432"
    volumes:
      - auth_db_data:/var/lib

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_ADMIN_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - auth_db
      - project_db

  auth_cache:
    image: redis:latest
    container_name: auth_cache
    ports:
      - "6379:6379"
    volumes:
      - auth_cache_data:/data

  project_db:
    image: postgres:15
    container_name: project_db
    environment:
      POSTGRES_DB: project_db
      POSTGRES_USER: ${PROJECT_DB_USER}
      POSTGRES_PASSWORD: ${PROJECT_DB_PASS}
    ports:
      - "5433:5432"
    volumes:
      - project_db_data:/var/lib

  projects_cache:
    image: redis:latest
    container_name: project_cache
    ports:
      - "6380:6379"
    volumes:
      - project_cache_data:/data

volumes:
  auth_db_data:
  project_db_data:
  auth_cache_data:
  project_cache_data:
